Make actions save artifacts immed. instead of at end

diff --git a/.github/workflows/build+appstoredeploy.yml b/.github/workflows/build+appstoredeploy.yml
--- a/.github/workflows/build+appstoredeploy.yml
+++ b/.github/workflows/build+appstoredeploy.yml
@@ -371,63 +371,6 @@ jobs:
           xcrun codesign --force --sign "${{ secrets.STORE_MACOS_CERTIFICATE_NAME }}" \
             --entitlements entitlements.xml --options runtime -v "${{ steps.build.outputs.appbundle }}"
       
-      - name: Package App
-        id: package
-        run: |
-          :
-          if [[ -z "${{ secrets.PKG_MACOS_CERTIFICATE_NAME }}" ]] ; then
-            echo "::error::Secret PKG_MACOS_CERTIFICATE_NAME not defined"
-            exit 1
-          fi
-          
-          # Build a pkg from the built app for uploading to App Store Connect
-          
-          packagefilename="${{ steps.version.outputs.archivename }}.pkg"
-          
-          echo "- Package app to make \"$packagefilename\""
-          xcrun productbuild --sign "${{ secrets.PKG_MACOS_CERTIFICATE_NAME }}" \
-            --component "${{ steps.build.outputs.appbundle }}" /Applications \
-            "${{ env.builddir }}/$packagefilename"
-          
-          echo "filename=$packagefilename" >> $GITHUB_OUTPUT
-          echo "file=${{ env.builddir }}/$packagefilename" >> $GITHUB_OUTPUT
-      
-      - name: Verify Package and AppStore Connect Acceess
-        id: connect
-        run: |
-          :
-          if [[ -z "${{ secrets.APPSTORECONNECT_APIKEY }}" ]] ; then
-            echo "::error::Secret APPSTORECONNECT_APIKEY not defined"
-            exit 1
-          fi
-          if [[ -z "${{ secrets.APPSTORECONNECT_APIKEYID }}" ]] ; then
-            echo "::error::Secret APPSTORECONNECT_APIKEYID not defined"
-            exit 1
-          fi
-          if [[ -z "${{ secrets.APPSTORECONNECT_APIISSUERID }}" ]] ; then
-            echo "::error::Secret APPSTORECONNECT_APIISSUERID not defined"
-            exit 1
-          fi
-          
-          # Turn our base64-encoded acess key back to a regular .p8 file
-          # in the expected subdirectory with the expected name containing the key id
-          
-          keyfilename="AuthKey_${{ secrets.APPSTORECONNECT_APIKEYID }}.p8"
-          keydir="private_keys"
-          mkdir "$keydir"
-          
-          echo "- Base64-decode key to make \"$keyfilename\""
-          echo "${{ secrets.APPSTORECONNECT_APIKEY }}" | base64 --decode > "./$keydir/$keyfilename"
-          # if deploying, this decoded key file will be used again by altool
-          
-          echo "- Run verification"
-          xcrun altool --validate-app --file "${{ steps.package.outputs.file }}" \
-            --type macos --apiKey "${{ secrets.APPSTORECONNECT_APIKEYID }}" \
-            --apiIssuer "${{ secrets.APPSTORECONNECT_APIISSUERID }}"
-          
-          echo "keyid=${{ secrets.APPSTORECONNECT_APIKEYID }}" >> $GITHUB_OUTPUT
-          echo "issuerid=${{ secrets.APPSTORECONNECT_APIISSUERID }}" >> $GITHUB_OUTPUT
-      
       - name: Release Notes
         id: notes
         run: |
@@ -479,19 +422,76 @@ jobs:
           echo "filename=$currentNotesFilename" >> $GITHUB_OUTPUT
           echo "file=${{ env.builddir }}/$currentNotesFilename" >> $GITHUB_OUTPUT
       
-      - name: Save Build Components as Artifact
+      - name: Save Build as Artifact
         uses: actions/upload-artifact@v4
         with:
-          name: "${{ steps.version.outputs.archivename }} App and Pkg"
+          name: "${{ steps.version.outputs.archivename }} (app-store)"
           path: |
             ${{ steps.build.outputs.appbundle }}
-            ${{ steps.package.outputs.file }}
+            ${{ steps.notes.outputs.file }}
       
-      - name: Save Release Notes as Artifact
+      - name: Package App
+        id: package
+        run: |
+          :
+          if [[ -z "${{ secrets.PKG_MACOS_CERTIFICATE_NAME }}" ]] ; then
+            echo "::error::Secret PKG_MACOS_CERTIFICATE_NAME not defined"
+            exit 1
+          fi
+          
+          # Build a pkg from the built app for uploading to App Store Connect
+          
+          packagefilename="${{ steps.version.outputs.archivename }}.pkg"
+          
+          echo "- Package app to make \"$packagefilename\""
+          xcrun productbuild --sign "${{ secrets.PKG_MACOS_CERTIFICATE_NAME }}" \
+            --component "${{ steps.build.outputs.appbundle }}" /Applications \
+            "${{ env.builddir }}/$packagefilename"
+          
+          echo "filename=$packagefilename" >> $GITHUB_OUTPUT
+          echo "file=${{ env.builddir }}/$packagefilename" >> $GITHUB_OUTPUT
+      
+      - name: Save Pkg as Artifact
         uses: actions/upload-artifact@v4
         with:
-          name: "${{ steps.version.outputs.archivename }} Release notes"
-          path: ${{ steps.notes.outputs.file }}
+          name: "${{ steps.version.outputs.archivename }} (app-store) Package"
+          path: ${{ steps.package.outputs.file }}
+      
+      - name: Verify Package and AppStore Connect Acceess
+        id: connect
+        run: |
+          :
+          if [[ -z "${{ secrets.APPSTORECONNECT_APIKEY }}" ]] ; then
+            echo "::error::Secret APPSTORECONNECT_APIKEY not defined"
+            exit 1
+          fi
+          if [[ -z "${{ secrets.APPSTORECONNECT_APIKEYID }}" ]] ; then
+            echo "::error::Secret APPSTORECONNECT_APIKEYID not defined"
+            exit 1
+          fi
+          if [[ -z "${{ secrets.APPSTORECONNECT_APIISSUERID }}" ]] ; then
+            echo "::error::Secret APPSTORECONNECT_APIISSUERID not defined"
+            exit 1
+          fi
+          
+          # Turn our base64-encoded acess key back to a regular .p8 file
+          # in the expected subdirectory with the expected name containing the key id
+          
+          keyfilename="AuthKey_${{ secrets.APPSTORECONNECT_APIKEYID }}.p8"
+          keydir="private_keys"
+          mkdir "$keydir"
+          
+          echo "- Base64-decode key to make \"$keyfilename\""
+          echo "${{ secrets.APPSTORECONNECT_APIKEY }}" | base64 --decode > "./$keydir/$keyfilename"
+          # if deploying, this decoded key file will be used again by altool
+          
+          echo "- Run verification"
+          xcrun altool --validate-app --file "${{ steps.package.outputs.file }}" \
+            --type macos --apiKey "${{ secrets.APPSTORECONNECT_APIKEYID }}" \
+            --apiIssuer "${{ secrets.APPSTORECONNECT_APIISSUERID }}"
+          
+          echo "keyid=${{ secrets.APPSTORECONNECT_APIKEYID }}" >> $GITHUB_OUTPUT
+          echo "issuerid=${{ secrets.APPSTORECONNECT_APIISSUERID }}" >> $GITHUB_OUTPUT
       
       - name: Deploy
         if: ${{ success() && steps.version.outputs.upload == 'true' }}
diff --git a/.github/workflows/build+release.yml b/.github/workflows/build+release.yml
--- a/.github/workflows/build+release.yml
+++ b/.github/workflows/build+release.yml
@@ -347,7 +347,7 @@ jobs:
           xcrun codesign --force --sign "${{ secrets.PROD_MACOS_CERTIFICATE_NAME }}" \
             --entitlements entitlements.xml --options runtime -v "${{ steps.build.outputs.appbundle }}"
       
-      - name: Notarize app bundle
+      - name: Notarize App Bundle
         run: |
           :
           if [[ -z "${{ secrets.PROD_MACOS_NOTARIZATION_APPLE_ID }}" ]] ; then
@@ -400,72 +400,6 @@ jobs:
           echo "- Attach staple"
           xcrun stapler staple "${{ steps.build.outputs.appbundle }}"
       
-      - name: Build Zip File
-        id: zip
-        run: |
-          :
-          archiveDir="${{ env.builddir }}/Sparkle"
-          archiveFileName="${{ steps.version.outputs.archivename }}.zip"
-          
-          echo "- Compress built app to \"$(basename $archiveDir)/$archiveFileName\""
-          mkdir "$archiveDir"
-          ditto -c -k --sequesterRsrc --keepParent "${{ steps.build.outputs.appbundle }}" \
-            "$archiveDir/$archiveFileName"
-          
-          echo "file=$archiveDir/$archiveFileName" >> $GITHUB_OUTPUT
-          echo "directory=$archiveDir" >> $GITHUB_OUTPUT
-      
-      - name: Disk Image
-        id: dmg
-        run: |
-          :
-          if ! command -v create-dmg >/dev/null 2>&1 ; then
-            echo "::warning::Required helper script not found: create-dmg. Skipping dmg creation"
-            # not sure if need to do `echo "file=whatever" >> $GITHUB_OUTPUT`
-            # to make release step work, or if empty/missing steps.dmg.output.file is ok
-            exit 0
-          fi
-          
-          imageDir="${{ env.builddir }}/Image"
-          imageFileName="${{ steps.version.outputs.archivename }}.dmg"
-          readmeFilename="${{ env.productname }} version ${{ steps.version.outputs.version }} read me.rtf"
-          
-          echo "- Copy built app to \"$(basename $imageDir)/${{ env.bundlename }}\""
-          mkdir "$imageDir"
-          ditto "${{ steps.build.outputs.appbundle }}" "$imageDir/${{ env.bundlename }}"
-          
-          echo "- Copy readme file from source repo to \"$(basename $imageDir)/$readmeFilename\""
-          cp "Designs/Cleepp/Cleepp download read me.rtf" "$imageDir/$readmeFilename"
-          
-          echo "- Build disk image \"${{ env.builddir }}/$imageFileName\""
-          create-dmg --hdiutil-quiet \
-            --volname "${{ steps.version.outputs.releasename }}" \
-            --window-size 540 160 --icon-size 64 \
-            --icon "$readmeFilename" 40 60 \
-            --icon "${{ env.bundlename }}" 200 60 \
-            --app-drop-link 360 60 \
-            "${{ env.builddir }}/$imageFileName" "$imageDir"
-          
-          echo "filename=${{ env.bundlename }}" >> $GITHUB_OUTPUT
-          echo "file=${{ env.builddir }}/$imageFileName" >> $GITHUB_OUTPUT
-          
-      - name: Sign and notarize disk image
-        run: |
-          :
-          echo "- Notarize disk image"
-          xcrun notarytool submit "${{ steps.dmg.outputs.file }}" --keychain-profile "notarytool-profile" --wait \
-            2>&1 | tee notarytool-out.txt
-          if [ ${PIPESTATUS[0]} -ne 0 ] || grep -q Invalid notarytool-out.txt ; then
-            if sed -nr '/^[[:space:]]*id: (.*)$/{s//\1/p;q;}' notarytool-out.txt > notarytool-id.txt ; then
-              echo "- Extract notarytool failure log"
-              xcrun notarytool log "$(<notarytool-id.txt)" --keychain-profile "notarytool-profile"
-            fi
-            exit 1
-          fi
-          
-          echo "- Attach staple"
-          xcrun stapler staple "${{ steps.dmg.outputs.file }}"
-      
       - name: Release Notes
         id: notes
         run: |
@@ -516,6 +450,86 @@ jobs:
           
           echo "filename=$currentNotesFilename" >> $GITHUB_OUTPUT
           echo "file=${{ env.builddir }}/$currentNotesFilename" >> $GITHUB_OUTPUT
+      
+      - name: Save Build as Artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: "${{ steps.version.outputs.archivename }} (non-app store)"
+          path: |
+            ${{ steps.build.outputs.appbundle }}
+            ${{ steps.notes.outputs.file }}
+      
+      - name: Build Zip File
+        id: zip
+        run: |
+          :
+          archiveDir="${{ env.builddir }}/Sparkle"
+          archiveFileName="${{ steps.version.outputs.archivename }}.zip"
+          
+          echo "- Compress built app to \"$(basename $archiveDir)/$archiveFileName\""
+          mkdir "$archiveDir"
+          ditto -c -k --sequesterRsrc --keepParent "${{ steps.build.outputs.appbundle }}" \
+            "$archiveDir/$archiveFileName"
+          
+          echo "file=$archiveDir/$archiveFileName" >> $GITHUB_OUTPUT
+          echo "directory=$archiveDir" >> $GITHUB_OUTPUT
+      
+      - name: Disk Image
+        id: dmg
+        run: |
+          :
+          if ! command -v create-dmg >/dev/null 2>&1 ; then
+            echo "::warning::Required helper script not found: create-dmg. Skipping dmg creation"
+            # not sure if need to do `echo "file=whatever" >> $GITHUB_OUTPUT`
+            # to make release step work, or if empty/missing steps.dmg.output.file is ok
+            exit 0
+          fi
+          
+          imageDir="${{ env.builddir }}/Image"
+          imageFileName="${{ steps.version.outputs.archivename }}.dmg"
+          readmeFilename="${{ env.productname }} version ${{ steps.version.outputs.version }} read me.rtf"
+          
+          echo "- Copy built app to \"$(basename $imageDir)/${{ env.bundlename }}\""
+          mkdir "$imageDir"
+          ditto "${{ steps.build.outputs.appbundle }}" "$imageDir/${{ env.bundlename }}"
+          
+          echo "- Copy readme file from source repo to \"$(basename $imageDir)/$readmeFilename\""
+          cp "Designs/Cleepp/Cleepp download read me.rtf" "$imageDir/$readmeFilename"
+          
+          echo "- Build disk image \"${{ env.builddir }}/$imageFileName\""
+          create-dmg --hdiutil-quiet \
+            --volname "${{ steps.version.outputs.releasename }}" \
+            --window-size 540 160 --icon-size 64 \
+            --icon "$readmeFilename" 40 60 \
+            --icon "${{ env.bundlename }}" 200 60 \
+            --app-drop-link 360 60 \
+            "${{ env.builddir }}/$imageFileName" "$imageDir"
+          
+          echo "filename=${{ env.bundlename }}" >> $GITHUB_OUTPUT
+          echo "file=${{ env.builddir }}/$imageFileName" >> $GITHUB_OUTPUT
+          
+      - name: Sign and Notarize Disk Image
+        run: |
+          :
+          echo "- Notarize disk image"
+          xcrun notarytool submit "${{ steps.dmg.outputs.file }}" --keychain-profile "notarytool-profile" --wait \
+            2>&1 | tee notarytool-out.txt
+          if [ ${PIPESTATUS[0]} -ne 0 ] || grep -q Invalid notarytool-out.txt ; then
+            if sed -nr '/^[[:space:]]*id: (.*)$/{s//\1/p;q;}' notarytool-out.txt > notarytool-id.txt ; then
+              echo "- Extract notarytool failure log"
+              xcrun notarytool log "$(<notarytool-id.txt)" --keychain-profile "notarytool-profile"
+            fi
+            exit 1
+          fi
+          
+          echo "- Attach staple"
+          xcrun stapler staple "${{ steps.dmg.outputs.file }}"
+      
+      - name: Save Disk Image as Artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: "${{ steps.version.outputs.archivename }} (non-app store) Disk Image"
+          path: ${{ steps.dmg.outputs.file }}
       
       - name: Setup Sparkle
         if: ${{ success() && steps.version.outputs.githubRelease == 'true' && steps.version.outputs.updateAppcast == 'true' && steps.version.outputs.tag }}
@@ -579,22 +593,6 @@ jobs:
           commit_message: Automated Change to appcast.xml
           file_pattern: "appcast.xml"
           status_options: "--untracked-files=no"
-      
-      - name: Save build as artifact
-        if: ${{ success() && !(steps.version.outputs.githubRelease == 'true' && steps.version.outputs.tag) }}
-        uses: actions/upload-artifact@v4
-        with:
-          name: Non-App Store build
-          path: |
-            ${{ steps.dmg.outputs.file }}
-      
-      - name: Save release notes as artifact
-        if: ${{ success() && !(steps.version.outputs.githubRelease == 'true' && steps.version.outputs.tag) }}
-        uses: actions/upload-artifact@v4
-        with:
-          name: Release notes
-          path: |
-            ${{ steps.notes.outputs.file }}
       
       - name: Draft Tagged Release
         if: ${{ success() && steps.version.outputs.githubRelease == 'true' && steps.version.outputs.tag }}
